apiVersion: v1
kind: Service
metadata:
  name: kgs-lb-svc
  labels:
    game-lb: kgs-lb
spec:
  type: LoadBalancer
  loadBalancerIP: "34.29.160.243"
  ports:
    - name: valheim3-port-1
      nodePort: 31636
      port: 31636
      protocol: UDP
      targetPort: 31636
    - name: valheim3-port-2
      nodePort: 31637
      port: 31637
      protocol: UDP
      targetPort: 31637
    - name: valheim3-port-3
      nodePort: 31638
      port: 31638
      protocol: UDP
      targetPort: 31638
    - name: valheim4-port-1
      nodePort: 31646
      port: 31646
      protocol: UDP
      targetPort: 31646
    - name: valheim4-port-2
      nodePort: 31647
      port: 31647
      protocol: UDP
      targetPort: 31647
    - name: valheim4-port-3
      nodePort: 31648
      port: 31648
      protocol: UDP
      targetPort: 31648
    - name: valheim6-port-1
      #nodePort: 31666
      port: 31666
      protocol: UDP
      targetPort: 31666
    - name: valheim6-port-2
      #nodePort: 31667
      port: 31667
      protocol: UDP
      targetPort: 31667
    - name: valheim6-port-3
      #nodePort: 31668
      port: 31668
      protocol: UDP
      targetPort: 31668
  selector:
    game-lb: kgs-lb
